Update 09-functions.yaml

diff --git a/.github/workflows/09-functions.yaml b/.github/workflows/09-functions.yaml
--- a/.github/workflows/09-functions.yaml
+++ b/.github/workflows/09-functions.yaml
@@ -6,19 +6,18 @@ jobs:
     ehco1:
         runs-on: ubuntu-latest
         steps:
-          - name: Failing step
-            run: exit 1
-          - name: I will be skipped
-            if: ${{ success() }}
-            run: echo "I will print if previous steps succeed."
-          - name: I will execute
-            if: ${{ failure() }}
-            run: echo "I will print if any previous step fails."
-          - name: I will execute
-            if: ${{ !cancelled() }}
-            run: echo "I will always print, except when the workflow is cancelled."
-          - name: I will execute when cancelled
-            if: ${{ cancelled() }}
-            run: echo "I will print if the workflow has been cancelled."
+            - name: Failing step
+              run: exit 1
+            - name: I will be executed
+              if: ${{ success() }}
+              run: echo "I will be print if previous steps succeed"
+            - name: I will execute
+              if: ${{ failure() }}
+              run: echo "i will print if any previous step fails"
+            - name: I will execute
+              if: ${{ !cancelled() }}
+              run: echo "i will print, if !cancelled"
+            - name: I will execute
+              if: ${{ cancelled() }}
+              run: echo "i will print, if cancelled"
  
-
